package aicq

import (
	"crypto/ed25519"
	"encoding/base64"
	"testing"
)

func TestCrossLanguagePythonToGo(t *testing.T) {
	// Ciphertext generated by Python aicq_crypto.encrypt_dm
	seedB64 := "brszxIZr+mq/YqAsbFEiG0HJCLc1bxdgqMeTMOYDyHo="
	ct := "cTbqkPRArnSGA2SichZJgNbOqtRD7WvOd3VV/iOoLRpF0GYf1WTZNMzYhvbXoXuTsR03gJ5RXgsxRgAM5ud23IiXA/YTdqGwNEwYnOvSvXgESFo="

	seed, _ := base64.StdEncoding.DecodeString(seedB64)
	priv := ed25519.NewKeyFromSeed(seed)

	pt, err := DecryptDM(ct, priv)
	if err != nil {
		t.Fatal(err)
	}
	if pt != "hello from Python to Go" {
		t.Fatalf("expected 'hello from Python to Go', got %q", pt)
	}
}

func TestCrossLanguageGoRoundTrip(t *testing.T) {
	// Use the same keypair, encrypt in Go and verify we can decrypt
	seedB64 := "brszxIZr+mq/YqAsbFEiG0HJCLc1bxdgqMeTMOYDyHo="
	pubB64 := "TDPr+5jVCCJlpZ/rqlwVbSEeVrB5L1yAzDdUE3CO1HU="

	seed, _ := base64.StdEncoding.DecodeString(seedB64)
	priv := ed25519.NewKeyFromSeed(seed)

	goCt, err := EncryptDM("hello from Go", pubB64)
	if err != nil {
		t.Fatal(err)
	}
	pt, err := DecryptDM(goCt, priv)
	if err != nil {
		t.Fatal(err)
	}
	if pt != "hello from Go" {
		t.Fatalf("expected 'hello from Go', got %q", pt)
	}
}
